### ISSUE TITLE
Changing firebase

### ISSUE THREAD

**Issue by NeerajCodz** [HarshAndroid/WeChat#2]
Hi Harsh, 
This is a really excellent app and I especially like its simplicity
Actually, I don't know much about flutter and I want to clone this repo run in android studio and change the firebase account to mine and use the app. Can you guide me on how to?

**Comment by HarshAndroid** [comment]
Thanks for Compliment.
Regarding changing Firebase:
1. Create New Firebase Project & Configure CLI & Update Firebase json Files (Video No.7 & 8 of Playlist)
2. Enable Firebase Cloud Firestore (Video No. 16) & Firebase Database (Video No. 30)
3. Update Firebase write rules (don't remember video no. but still work for 1 month without updating rules).

And You're Done.
Playlist Link: https://www.youtube.com/playlist?list=PL8kbUJtS6hyal7Uw7wTeYmv7yiNPH5kOq

**Comment by NeerajCodz** [comment]
Thank you so much for you reply.
I have an another question too is there anyway to change the package name of the app

**Comment by HarshAndroid** [comment]
Refer below article for changing package name or alternatively you can use below package too.
Article: https://stackoverflow.com/questions/51534616/how-to-change-package-name-in-flutter
Package: https://pub.dev/packages/change_app_package_name

**Comment by NeerajCodz** [comment]
I am done with all your steps now can you tell me how to generate apk file

**Comment by HarshAndroid** [comment]
Simply run this command in terminal.
flutter run --release and then inside build/outputs/flutter-apk/ you will find release apk file.
